name: Flutter Web Build and Deploy

on:
  push:
    branches: main
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Web App
        run: flutter build web --web-renderer html --release
      - name: Modify Index HTML
        run: |
          cd build/web
          sed -i 's/<base href="\/">/<base href=".\/">/' index.html
      
      - name: Deploy Flutter build
        run: |
          git checkout -b gh-pages
          cp -r ./build/web/* .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Flutter web build"
          git push -f origin gh-pages
